name: Build and GH-Page Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run: npm run install

      - name: Build
        run: |
          npm run init
          npm run front-prod

      - name: Deploy to GH Page
        uses: jessica-shi/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs